# Le nom de ton automatisation (tu peux mettre ce que tu veux)
name: Premier Test de Secret

# Événement : le robot se déclenche à chaque fois qu'on fait un "git push"
on: [push]

# La liste des tâches que le robot doit accomplir
jobs:
  mon-premier-job:
    # On demande à GitHub de nous prêter une machine virtuelle Ubuntu toute propre
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Le robot télécharge le code de ton dépôt pour pouvoir travailler
      - name: Recuperer le code du projet
        uses: actions/checkout@v4

      # Étape 2 : Le robot exécute une commande dans le terminal d'Ubuntu
      - name: Afficher le secret de maniere securisee
        run: |
          echo "Regarde, GitHub va masquer mon secret ci-dessous :"
          echo "${{ secrets.SUPER_SECRET_PASSWORD }}"